spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.bhnbgnrlhoerkcwjzrgh}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:xinlin630379503}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

spring.main.lazy-initialization=true

server.port=${PORT:8080}

jwt.secret=Zk9zT0p3dW5wU0h1Y2lJQ0F4YlR2RzF5c2NwN1A=
jwt.expiration=3600000